@startuml
title Figure 10.6 Aggregation and Compostion
left to right direction
class Name
class Student
class Address
Name"1"---*"1"Student : compostion
Student "1,,3" o---"1"Address : aggregation
@enduml
