@startuml exercise10.10
title Exercise 10.10 - Queue Class
class Queue {
    -elements: int[]
    -size: size
    +Queue()
    +enqueue(v: int): void
    +dequeue(): int
    +empty(): boolean
    +getSize(): int
}
@enduml
