@startuml exer10.1
title Exercise 10.1
class Time {
    -hour: long
    -minute: long
    -second: long

    +Time()
    +Time(elapseTime: long)
    +Time(hour: long, minute: long, second: long)

    +getHour(): long
    +getMinute(): long
    +getSecond(): long
    +setTime(elapseTime: long)
}
@enduml
