@startuml
class Stock {
    +symbol: String
    +name: String
    +previousClosingPrice: double
    +currentPrice: double
    +Stock(symbol: String, name: String)
    +getChangePercent(): double
}
@enduml
