@startuml
class StopWatch {
    -startTime: long
    -endTime: long
    +StopWatch()
    +start(): void
    +stop(): void
    +getElapsedTime(): long
    +getStartTime(): long
    +getEndTime(): long
}
@enduml
