@startuml exercise10.3
title Exercise 10.3 MyInteger
class MyInteger {
    -value: int

    +MyInteger(data: int)
    +getValue(): int

    +isEven(): boolean
    +isOdd(): boolean
    +isPrime(): boolean

    +{static} isEven(value: int): boolean
    +{static} isOdd(value: int): boolean
    +{static} isPrime(value: int): boolean

    +{static} isEven(value: MyInteger): boolean
    +{static} isOdd(value: MyInteger): boolean
    +{static} isPrime(value: MyInteger): boolean

    +equals(value: int): boolean
    +equals(value: MyInteger): boolean

    +{static}parseInt(value: String): MyInteger
    +{static}parseInt(values[] char[]) : MyInteger
}
@enduml
