@startuml
class MyInteger {
    -value: int

    +MyInteger(data: int)
    +getValue(): int

    +isEven(): boolean
    +isOdd(): boolean
    +isPrime(): boolean

    +{static} isEven(value: MyInteger): boolean
    +{static} isOdd(value: MyInteger): boolean
    +{static} isPrime(value: MyInteger): boolean

    +equals(value: int): boolean
    +equals(value: MyInteger): boolean

    +parseInt(value: String): MyInteger
    +parseInt(values[] char[]) : MyInteger
}
@enduml
