@startuml
class Circle {
    -radius: double
    -{static}numberOfObjects: int
    +Circle()
    +Circle(radius: double)
    +setRadius(radius: double): void
    +getRadius(): double
    +{static}getNumberOfObjects(): int
    +getArea(): double
}
@enduml
