@startuml relation2
title Relations between classes 2
    class Class11 { 
    }
    class Class12 { 
    }
    class Class13 { 
    }
    class Class14 { 
    }
    class Class15 { 
    }
    class Class16 { 
    }
    class Class17 { 
    }
    class Class18 { 
    }
    class Class19 { 
    }
    class Class20 { 
    }
    
    Class11 <|.. Class12
    Class13 --> Class14
    Class15 ..> Class16
    Class17 ..|> Class18
    Class19 <--* Class20
@endum