@startuml
class MyPoint {
    -x: double
    -y: double

    +MyPoint()
    +MyPoint(x: double, y: double)

    +getX(): double
    +gety(): double
    +distance(point: MyPoint): double
    +distance(x: double, y:double): double
    +{static} distance(point1: MyPoint, point2: MyPoint): double
}
@enduml
