@startuml Exercise10.11
title Exercise 10.11 - Circle2D Class
class Circle2D {
    -x: double
    -y: double
    -radius: double

    +Circle2D()
    +Circle2D(x: double, y: double: radius: double)

    +getRadius(): double
    +getArea(): double
    +getPerimeter(): double
    +contains(x: double, y: double): boolean
    +contains(circle: Circle2D): boolean
    +overlaps(circle: Circle2d): boolean
}
@enduml
